[package]
name = "typst-math-wasm-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"

[dependencies.typst-math-wasm]
path = ".."

[[bin]]
name = "compile_math"
path = "fuzz_targets/compile_math.rs"
test = false
doc = false
bench = false

[workspace]
