[package]
name = "formatter-core-fuzz"
version = "0.0.0"
edition = "2024"
publish = false

[profile.release]
debug-assertions = false
debug = true

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"

[dependencies.formatter-core]
path = ".."

[[bin]]
name = "fuzz_target_1"
path = "fuzz_targets/fuzz_target_1.rs"
test = false
doc = false
bench = false

[workspace]
